### PR TITLE
modules updated

### PR DESCRIPTION
**Pull request by leonelhs**
I have updated this project to last keras and retinaface versions. I would be nice keep this project updated for others researchers.

### CODE REVIEW

**Comment by david-svitov** [comment]
Hi! Thank you for your interest in the project. To accept the pull request you must first delete all __pycache__ folders and .pyc files

**Comment by leonelhs** [comment]
done, pycache files deleted.

**Comment by seancarroll** [comment]
@leonelhs I was doing something similar then found this PR. I noticed when I run it in a notebook I'm getting a strange output. Curious if you've seen something similar in your testing

I should note that I initially I got the following `Cannot assign value to variable ' instance_normalization_9/gamma:0': Shape mismatch.The variable shape (128,), and the assigned value shape (1,) are incompatible.`. The initial way I attempted to solve it was via `model.load_weights('./saved_model/faces_bald_InsNorm_4x4_D2/model_G_5_170.hdf5', by_name=True, skip_mismatch=True)` but this seems wrong and likely the culprit. 

image

**Comment by seancarroll** [comment]
Issue stemmed from trying to use `from tensorflow_addons.tfa import InstanceNormalization`

**Comment by david-svitov** [comment]
@seancarroll yes, it looks like issue with loading weights to `InstanceNormalization`. I will check next week how to modify the checkpoint to load weights using `tensorflow_addons`

**Comment by david-svitov** [comment]
@seancarroll I checked and accepted this pull request. You can use version from master branch now, it works. 
@leonelhs Thanks again for your contribution.

**Comment by leonelhs** [comment]
O yes, I'm sorry , since I was working on how to make it running , I complete forget that the source was coming   from a jupyter notebook, so I forget to update it, Nevertheless already I have update it an tested getting successfully result. 
  
test_baldgan

**Pull request merged**
